# Generated by Django 5.1.3 on 2024-12-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_status_4a0a95_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ACTIVЕ', 'Активна'), ('DONE', 'Выполнена')], default='ACTIVЕ', max_length=11, verbose_name='Статус'),
        ),
    ]
